# Imports

In [3]:
import pandas as pd
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import math

# Loading data

In [4]:
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size = 0.2)
# boston.data[0,:]
# x_train
df = pd.DataFrame(boston.data)
df.columns = boston.feature_names
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

# Linear Regression

In [5]:
def fit(x, y):
    theta = np.zeros(x.shape[1])
    feature_numbers = x.shape[1]
    m = len(y)
    for i in range(feature_numbers):
        x_mean = 0
        y_mean = y.mean()
        xy_mean = 0
        x2_mean = 0
        for j in range(m):
            x_mean += (1/m) * (x[j][i])
            xy_mean += (1/m) * (x[j][i]*y[j])
            x2_mean += (1/m) * (x[j][i]**2)
        numerator = x_mean*y_mean - xy_mean
        denominator = x_mean**2 - x2_mean
        theta[i] = numerator/denominator
    theta_x_sum = 0
    for i in range(feature_numbers):
        x_mean = 0
        for j in range(m):
            x_mean += (1/m)*x[j][i]
        theta_x_sum += theta[i]*x_mean
    theta0 = y_mean - theta_x_sum
    return theta, theta0

def predict(x, theta, theta0):
    m = x.shape[0]
    feature_numbers = x.shape[1]
    predictions = np.zeros(m)
    for i in range(m):
        theta_x_sum = 0
        for j in range(feature_numbers):
            theta_x_sum += theta[j]*x[i][j]
        predictions[i] = theta_x_sum + theta0
    return predictions

def score(x, y, theta, theta0):
    y_predicted = predict(x, theta, theta0)
    m = len(y)
    u = 0
    v = 0
    for i in range(m):
        u += (y[i] - y_predicted[i])**2
        v += (y[i] - y.mean())**2
    R = (1 - (u/v))
    return R

def feature_scaling(x, y):
    m = len(y)
    feature_numbers = x.shape[1]
    for i in range(feature_numbers):
        mean = 0
        for k in range(m):
            mean += (1/m) * x[k][i]
        for j in range(m):
            x[j][i] = (x[j][i] - mean)


In [6]:
clf = LinearRegression()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.7538094957837882

In [7]:
# feature_scaling(x_train, y_train)
# feature_scaling(x_test, y_test)
theta, theta0 = fit(x_train,y_train)
print(score(x_test, y_test, theta, theta0))
yp = predict(x_test, theta, theta0)
# y_train.mean()
yp

-7.866187654443539


array([ 79.52303637, -19.94809644,  58.55528658,   2.45048161,
        47.98757963,  67.31440846,  71.2868524 , -34.51652868,
        22.15027082,  61.20283139,  67.13434559, -15.53159196,
       -53.44866464,  78.38031725,  11.92436202,  67.14201682,
       -15.12240007, -13.41299631,  27.09152192, -19.41300073,
        64.50414937, -23.20333421,  67.7494149 ,  11.90106053,
         3.37811543,  88.97058706,  57.17609887,   6.41624244,
        -6.37112514, -46.18354315,  29.42079508,  16.08598488,
        27.73307622,  56.94029662,  60.41977251, -22.91285777,
        47.89938607,  38.73835705, 102.12956173,  24.98410164,
       -13.96185881,  65.80913126,  18.1811426 , -35.91783525,
        16.20149662,  58.09954925,   5.59460842,  32.87018491,
        15.59403337,  34.61468372, -10.03821253, -20.85771536,
         2.05127291,  29.50229022, -23.92678948,  52.21591556,
       -19.00496464,  36.92101575,  43.85429082,  35.27708892,
        -8.35362494,  50.47366867,  18.73587124,  43.41

# Gradient Descent for single dimension

In [8]:
def step_gradient(x, y, learning_rate, m_current, b_current):
    m_slope = 0
    b_slope = 0
    n = len(y)
    for i in range(n):
        m_slope += (-2/n)(y[i] - m_current*x - b_current)*x
        b_slope += (-2/n)(y[i] - m_current*x - b_current)
    new_m = m_current - learning_rate*m_slope
    new_b = b_current - learning_rate*b_slope
    return new_m, new_b

def cost_gd(x, y, m, b):
    cost = 0
    for i in range(len(y)):
        cost += (y[i] - m*x[i] -b)**2
    return cost/len(y)

def gd_runner(x, y, learning_rate, num_iterations = 1000):
    m_current = 0
    b_current = 0
    print("Start Cost", cost_gd(x, y, m_current, b_current))
    for i in range(num_iterations):
        m_current, b_current = step_gradient(x, y, learning_rate, m_current, b_current)
    print("Final Cost", cost_gd(x, y, m_current, b_current))
        # we can print cost at every step

# Gradient Descent for n dimensions

In [93]:
def step_gradient(x, y, learning_rate, m_current, b_current):
    m_slope = np.zeros(x.shape[1])
    b_slope = 0
    new_m = np.zeros(x.shape[1])
    n = x.shape[0]
    for i in range(x.shape[1]):
        for j in range(n):
            m_slope[i] += ((-2/n)*(y[j] - (m_current*x[j]).sum() - b_current)*x[j,i])
            new_m[i] = m_current[i] - (learning_rate*m_slope[i])
            b_slope += ((-2/n)*(y[i] - (m_current*x[i]).sum() - b_current))
            new_b = b_current - learning_rate*b_slope
#     for i in range(n):
        
    
    return new_m, new_b


def cost_gd(x, y, m, b):
    total_cost = 0
    n = len(y)
    for i in range(n):
        sum_mx = 0
        for j in range(x.shape[1]):
            sum_mx += m[j]*x[i,j]
        total_cost += (y[i] - sum_mx - b)**2
    return total_cost/n


def gd_runner(x, y, learning_rate = 0.0001, num_iterations = 15):
    m_current = np.zeros(x.shape[1])
    b_current = 0
    print("Start Cost", cost_gd(x, y, m_current, b_current))
    for i in range(num_iterations):
        m_current, b_current = step_gradient(x, y, learning_rate, m_current, b_current)
    print("Final Cost", cost_gd(x, y, m_current, b_current))
    return m_current, b_current


def predict_gd(x, theta, theta0):
    m = x.shape[0]
    predictions = np.zeros(m)
    feature_numbers = x.shape[1]
    for i in range(m):
        theta_x_sum = 0
        for j in range(feature_numbers):
            theta_x_sum += theta[j]*x[i,j]
        predictions[i] = theta_x_sum + theta0
    return predictions

In [122]:
theta, theta0 = gd_runner(x_train, y_train, 0.0000027, 500)
predict_gd(x_test, theta, theta0)

Start Cost 592.8874257425739
Final Cost 68.71381674454024


array([27.47479814, 23.66898587, 27.65326351, 23.9591709 , 23.13469464,
       29.84052394, 26.48057178, 22.85597314, 22.84900955, 26.42130361,
       29.12594931, 21.28767215, 16.44139462, 24.0454068 , 22.31431831,
       24.64368308, 20.73389863, 10.90918418, 23.23967581, 18.66101993,
       29.63675263,  4.67383436, 25.59680683, 23.00113594, 23.83975887,
       29.83944978, 23.44009755, 21.4875837 , 23.28343963, 22.32237662,
       23.20007378, 23.35997137, 24.64938675, 28.51859528, 26.70441429,
       23.46862755, 21.22709257, 23.24573845, 30.52417756, 23.59543825,
       21.38491472, 26.40457842, 18.52987001, 23.18034872, 23.29636847,
       21.42575504, 23.01496981, 22.60171759, 23.57073662, 22.90501917,
       23.66073143, 23.51839144, 23.34324211, 23.49719127,  2.06895818,
       28.80809138, 22.51177678, 22.27104764, 22.67582812, 23.14097908,
       23.33211819, 24.95154133, 23.05535192, 22.31433667, 19.62377984,
       20.49012171, 22.5961941 , 23.74874559, 20.86884503, 23.83

In [123]:
y_test

array([30.3, 15.1, 22.3, 18. , 26.6, 28.5, 36.4,  5.6, 21.7, 20.1, 30.8,
       19.1,  8.8, 46. , 20.3, 50. , 17.8, 13.8, 22.4, 13. , 27.9, 14.1,
       50. , 14.4, 17.1, 50. , 36.2, 12.7, 19.1,  7.4, 16.6, 18.3, 18.5,
       20.6, 32. ,  8.5, 22.6, 23.8, 50. , 21.5, 19.9, 32.4, 23.8,  9.7,
       20.4, 46.7, 19.7, 23.3, 19.4, 19. , 16.7,  7.2, 23. , 26.4, 13.4,
       18.2, 12.1, 20. , 31.6, 20.4, 13.3, 24.8, 17.8, 21.2, 17. , 27.9,
       25. , 17.8, 15.4, 22.8, 27. , 21.4, 19.6, 19.3, 20.7, 24.3, 23.1,
       12.5, 17.3, 41.7, 50. , 20.8, 28.1, 22. , 21.9, 17.1, 10.4, 13.4,
        8.8, 20.1, 16.5, 34.6, 16. , 20.8, 24.3, 24.5, 17.7, 13.9, 22.2,
       22. , 22. , 20.6])